# Join node to the tailnet (initial connection uses LAN IP)
module "tailnet-provision-node" {
  source                  = "./modules/tailnet-provision-node"
  server_ip               = var.node_server_ip
  ssh_user                = var.node_ssh_user
  ssh_priv_key            = trimspace(file(var.ssh_priv_key_path))
  nomad_hostname          = var.node_host_name
  headscale_server_domain = data.terraform_remote_state.homelab.outputs.headscale_server_fqdn
  tailnet_auth_key        = data.terraform_remote_state.homelab.outputs.node_preauth_key

  providers = {
    headscale = headscale
  }
}

# After tailnet join, all subsequent connections use the Tailscale hostname
module "node-infra-tls" {
  source                = "./../templates/infra-tls"
  account_key_pem       = data.terraform_remote_state.homelab.outputs.acme_account_key_pem
  server_domain         = "${var.node_host_name}.${var.headscale_subdomain}.${var.headscale_magic_domain}"
  aws_region            = var.aws_region
  aws_access_key        = var.aws_access_key
  aws_secret_key        = var.aws_secret_key
  recursive_nameservers = var.recursive_nameservers

  depends_on = [module.tailnet-provision-node]
  providers = {
    acme = acme
  }
}

module "node-provision-tls" {
  source            = "./../templates/provision-tls"
  server_ip         = "${var.node_host_name}.${var.headscale_subdomain}.${var.headscale_magic_domain}"
  ssh_user          = var.node_ssh_user
  ssh_priv_key      = trimspace(file(var.ssh_priv_key_path))
  domain            = module.node-infra-tls.certificate_domain
  tls_privkey_pem   = module.node-infra-tls.privkey_pem
  tls_fullchain_pem = module.node-infra-tls.fullchain_pem
  depends_on        = [module.node-infra-tls]
}

module "node-provision-dep" {
  source       = "./modules/node-provision-dep"
  server_ip    = module.node-infra-tls.certificate_domain
  ssh_user     = var.node_ssh_user
  ssh_priv_key = trimspace(file(var.ssh_priv_key_path))
  depends_on   = [module.tailnet-provision-node, module.node-infra-tls]
}

module "cluster-provision" {
  source                    = "./modules/node-provision-server"
  host                      = module.node-infra-tls.certificate_domain
  ssh_user                  = var.node_ssh_user
  ssh_priv_key              = trimspace(file(var.ssh_priv_key_path))
  nomad_host_name           = var.node_host_name
  headscale_magic_subdomain = "${var.headscale_subdomain}.${var.headscale_magic_domain}"
  registry_domain           = data.terraform_remote_state.homelab.outputs.tailnet_user_name_map["registry_server_user"]
  # Hostname is decoupled from headscale username — `registry_proxy_server_user`
  # remains "registry-proxy" so additional mirrors (registry-quayio, etc.) can
  # share the same headscale identity / ACL group while taking distinct
  # TS_HOSTNAMEs. This literal must match var.registry_dockerio_domain in the
  # nextcloud deployment.
  registry_dockerio_domain  = "registry-dockerio"
  depends_on                = [module.node-provision-dep]
}

# Wide host-side backup of delphi: /etc, /home, /root, /var/lib/rancher/k3s.
# Velero already covers cluster API + PVC data; this layer catches manual host
# changes, SSH keys, anything outside the cluster, and provides a redundant
# copy of the K3s data dir for true paranoia. Velero remains the primary path
# for cluster restore — kopia is the safety net for the host itself.
module "delphi-provision-kopia" {
  source                = "./../templates/provision-kopia"
  server_ip             = module.node-infra-tls.certificate_domain
  ssh_user              = var.node_ssh_user
  ssh_priv_key          = trimspace(file(var.ssh_priv_key_path))
  bucket_name           = data.terraform_remote_state.homelab.outputs.backup_bucket_name
  bucket_region         = data.terraform_remote_state.homelab.outputs.backup_bucket_region
  prefix                = data.terraform_remote_state.homelab.outputs.backup_prefixes["delphi"]
  aws_access_key_id     = data.terraform_remote_state.homelab.outputs.backup_iam_keys["delphi"].access_key_id
  aws_secret_access_key = data.terraform_remote_state.homelab.outputs.backup_iam_keys["delphi"].secret_access_key
  repo_password         = data.terraform_remote_state.homelab.outputs.backup_repo_passwords["delphi"]
  # /var/lib/rancher/k3s is owned by Velero — `storage/` (local-path PVCs) flows
  # through FSB into the cluster-${cluster_name}/velero/ prefix, and cluster API
  # state (etcd/sqlite, manifests, certs, node-token) is regenerated by re-
  # applying the cluster deployment. Backing it up via kopia would double ~100G
  # of PVC bytes for no recovery benefit.
  backup_paths = ["/etc", "/root"]
  exclude_globs = [
    "**/.cache",
    "**/node_modules",
    "**/.venv",
    "**/__pycache__",
  ]
  on_calendar = "daily"
  depends_on  = [module.cluster-provision]
}
